// <auto-generated />
using System;
using DealerManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DealerManagement.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719155549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OldValues")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", "Logging");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ErrorDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<string>("RequestBody")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs", "Logging");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 164, DateTimeKind.Utc).AddTicks(3613),
                            Description = "Can view dealers",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Dealers",
                            PermissionName = "Dealers.View",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 164, DateTimeKind.Utc).AddTicks(3617)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5276),
                            Description = "Can create dealers",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Dealers",
                            PermissionName = "Dealers.Create",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5280)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5308),
                            Description = "Can edit dealers",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Dealers",
                            PermissionName = "Dealers.Edit",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5308)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5312),
                            Description = "Can delete dealers",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Dealers",
                            PermissionName = "Dealers.Delete",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5312)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5315),
                            Description = "Can export dealers",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Dealers",
                            PermissionName = "Dealers.Export",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5316)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5330),
                            Description = "Can view orders",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Orders",
                            PermissionName = "Orders.View",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5330)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5335),
                            Description = "Can create orders",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Orders",
                            PermissionName = "Orders.Create",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5335)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5338),
                            Description = "Can edit orders",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Orders",
                            PermissionName = "Orders.Edit",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5338)
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5341),
                            Description = "Can delete orders",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Orders",
                            PermissionName = "Orders.Delete",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5341)
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5346),
                            Description = "Can export orders",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Orders",
                            PermissionName = "Orders.Export",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5346)
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5349),
                            Description = "Can view products",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Products",
                            PermissionName = "Products.View",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5350)
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5414),
                            Description = "Can create products",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Products",
                            PermissionName = "Products.Create",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5415)
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5418),
                            Description = "Can edit products",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Products",
                            PermissionName = "Products.Edit",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5418)
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5421),
                            Description = "Can delete products",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Products",
                            PermissionName = "Products.Delete",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5422)
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5424),
                            Description = "Can export products",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Products",
                            PermissionName = "Products.Export",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5425)
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5427),
                            Description = "Can view reports",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Reports",
                            PermissionName = "Reports.View",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5428)
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5431),
                            Description = "Can create reports",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Reports",
                            PermissionName = "Reports.Create",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5432)
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5437),
                            Description = "Can edit reports",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Reports",
                            PermissionName = "Reports.Edit",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5437)
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5440),
                            Description = "Can delete reports",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Reports",
                            PermissionName = "Reports.Delete",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5440)
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5443),
                            Description = "Can export reports",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Reports",
                            PermissionName = "Reports.Export",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5443)
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5446),
                            Description = "Can view users",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Users",
                            PermissionName = "Users.View",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5447)
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5450),
                            Description = "Can create users",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Users",
                            PermissionName = "Users.Create",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5450)
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5453),
                            Description = "Can edit users",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Users",
                            PermissionName = "Users.Edit",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5453)
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5456),
                            Description = "Can delete users",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Users",
                            PermissionName = "Users.Delete",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5457)
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5459),
                            Description = "Can export users",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Users",
                            PermissionName = "Users.Export",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5459)
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5462),
                            Description = "Can view settings",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Settings",
                            PermissionName = "Settings.View",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5463)
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5466),
                            Description = "Can create settings",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Settings",
                            PermissionName = "Settings.Create",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5466)
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5469),
                            Description = "Can edit settings",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Settings",
                            PermissionName = "Settings.Edit",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5469)
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5472),
                            Description = "Can delete settings",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Settings",
                            PermissionName = "Settings.Delete",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5473)
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5475),
                            Description = "Can export settings",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Settings",
                            PermissionName = "Settings.Export",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5476)
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5478),
                            Description = "Can view inventory",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Inventory",
                            PermissionName = "Inventory.View",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5479)
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5483),
                            Description = "Can create inventory",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Inventory",
                            PermissionName = "Inventory.Create",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5483)
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5486),
                            Description = "Can edit inventory",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Inventory",
                            PermissionName = "Inventory.Edit",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5487)
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5491),
                            Description = "Can delete inventory",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Inventory",
                            PermissionName = "Inventory.Delete",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5491)
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5494),
                            Description = "Can export inventory",
                            IsActive = true,
                            IsDeleted = false,
                            Module = "Inventory",
                            PermissionName = "Inventory.Export",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 185, DateTimeKind.Utc).AddTicks(5494)
                        });
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 161, DateTimeKind.Utc).AddTicks(9077),
                            Description = "Full system access",
                            IsActive = true,
                            IsDeleted = false,
                            RoleName = "SuperAdmin",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 161, DateTimeKind.Utc).AddTicks(9084)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 162, DateTimeKind.Utc).AddTicks(974),
                            Description = "Administrative access",
                            IsActive = true,
                            IsDeleted = false,
                            RoleName = "Admin",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 162, DateTimeKind.Utc).AddTicks(975)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 162, DateTimeKind.Utc).AddTicks(978),
                            Description = "Managerial access",
                            IsActive = true,
                            IsDeleted = false,
                            RoleName = "Manager",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 162, DateTimeKind.Utc).AddTicks(979)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 162, DateTimeKind.Utc).AddTicks(981),
                            Description = "Sales operations",
                            IsActive = true,
                            IsDeleted = false,
                            RoleName = "SalesPerson",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 162, DateTimeKind.Utc).AddTicks(981)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 162, DateTimeKind.Utc).AddTicks(983),
                            Description = "Basic user access",
                            IsActive = true,
                            IsDeleted = false,
                            RoleName = "User",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 162, DateTimeKind.Utc).AddTicks(983)
                        });
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions", "Auth");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResetTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 186, DateTimeKind.Utc).AddTicks(2039),
                            Email = "admin@dealerapp.com",
                            FailedLoginAttempts = 0,
                            FirstName = "System",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Administrator",
                            PasswordHash = "$2a$11$K5pF7qR8tY9hJ3kL2mN4oOvWxZ6cB3dE1fG8hI2jK5lM7nO4pQ2rS",
                            PhoneNumber = "+1234567890",
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 186, DateTimeKind.Utc).AddTicks(2041),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 190, DateTimeKind.Utc).AddTicks(3480),
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 1,
                            UpdatedDate = new DateTime(2026, 7, 19, 15, 55, 47, 190, DateTimeKind.Utc).AddTicks(3486),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Config.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SettingType")
                        .HasColumnType("int");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("AppSettings", "Config");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Dealer.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DealerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DealerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DealerType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentTermsDays")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DealerCode")
                        .IsUnique();

                    b.HasIndex("DealerName");

                    b.HasIndex("Status");

                    b.ToTable("Dealers", "Dealer");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Dealer.DealerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AddressType")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("DealerAddresses", "Dealer");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Dealer.DealerContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("DealerContacts", "Dealer");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Finance.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Invoices", "Finance");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Finance.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReceivedBy")
                        .HasColumnType("int");

                    b.Property<int?>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ReceivedByUserId");

                    b.ToTable("Payments", "Finance");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Finance.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TaxType")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Taxes", "Finance");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Inventory.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastStockDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxStockLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinStockLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantityReserved")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ProductId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("Stock", "Inventory");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Inventory.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockMovements", "Inventory");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Inventory.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseCode")
                        .IsUnique();

                    b.ToTable("Warehouses", "Inventory");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Notification.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", "Notification");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Product.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Brands", "Product");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Product.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories", "Product");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxOrderQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("SKU");

                    b.ToTable("Products", "Product");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Sales.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SalesPersonId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("SalesPersonId");

                    b.HasIndex("Status");

                    b.ToTable("Orders", "Sales");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Sales.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", "Sales");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.AuditLog", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Auth.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealerManagement.Domain.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.UserRole", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealerManagement.Domain.Entities.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Dealer.DealerAddress", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Dealer.Dealer", "Dealer")
                        .WithMany("Addresses")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Dealer.DealerContact", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Dealer.Dealer", "Dealer")
                        .WithMany("Contacts")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Finance.Invoice", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Dealer.Dealer", "Dealer")
                        .WithMany("Invoices")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerManagement.Domain.Entities.Sales.Order", "Order")
                        .WithOne("Invoice")
                        .HasForeignKey("DealerManagement.Domain.Entities.Finance.Invoice", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Finance.Payment", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Dealer.Dealer", "Dealer")
                        .WithMany("Payments")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerManagement.Domain.Entities.Sales.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerManagement.Domain.Entities.Auth.User", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId");

                    b.Navigation("Dealer");

                    b.Navigation("Order");

                    b.Navigation("ReceivedByUser");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Inventory.Stock", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Product.Product", "Product")
                        .WithMany("StockLevels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerManagement.Domain.Entities.Inventory.Warehouse", "Warehouse")
                        .WithMany("StockLevels")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Inventory.StockMovement", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Sales.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DealerManagement.Domain.Entities.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerManagement.Domain.Entities.Inventory.Warehouse", "Warehouse")
                        .WithMany("StockMovements")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Notification.Notification", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Product.Category", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Product.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Product.Product", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Product.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DealerManagement.Domain.Entities.Product.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Sales.Order", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Dealer.Dealer", "Dealer")
                        .WithMany("Orders")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerManagement.Domain.Entities.Auth.User", "SalesPerson")
                        .WithMany()
                        .HasForeignKey("SalesPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dealer");

                    b.Navigation("SalesPerson");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Sales.OrderItem", b =>
                {
                    b.HasOne("DealerManagement.Domain.Entities.Sales.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealerManagement.Domain.Entities.Product.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Dealer.Dealer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");

                    b.Navigation("Invoices");

                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Inventory.Warehouse", b =>
                {
                    b.Navigation("StockLevels");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Product.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Product.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Product.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("StockLevels");
                });

            modelBuilder.Entity("DealerManagement.Domain.Entities.Sales.Order", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
