// ─────────────────────────────────────────────────────────────────────────────
// src/types/dealer.types.ts
//
// WHY THIS FILE EXISTS:
//   All dealer-related data shapes are defined here.
//   These types mirror the SQL Server "Dealers" table exactly.
//
// SQL SERVER TABLE: Dealers
//   DealerId       INT IDENTITY PRIMARY KEY
//   DealerName     NVARCHAR(150)
//   ContactPerson  NVARCHAR(100)
//   Phone          NVARCHAR(20)
//   Email          NVARCHAR(150)
//   Address        NVARCHAR(300)
//   City           NVARCHAR(100)
//   Status         BIT DEFAULT 1
//   CreatedDate    DATETIME DEFAULT GETDATE()
// ─────────────────────────────────────────────────────────────────────────────

// ── Dealer ────────────────────────────────────────────────────────────────────
// Represents one row from the Dealers table.
// This is what the API returns for GET /api/dealers/:id
export interface Dealer {
  dealerId: number;              // INT IDENTITY — primary key
  dealerName: string;            // NVARCHAR(150) — business name
  /** LN / dealer code from API DealerCode */
  dealerCode?: string | null;
  contactPerson: string | null;  // NVARCHAR(100) — contact name
  phone: string | null;          // NVARCHAR(20)
  email: string | null;          // NVARCHAR(150)
  address: string | null;        // NVARCHAR(300) — full street address
  city: string | null;           // NVARCHAR(100)
  /** Credit limit from API (shown as Available Credit on profile) */
  creditLimit?: number;
  status: boolean;               // BIT — true = active, false = inactive
  createdDate: string;           // DATETIME as ISO string
}

// ── Create Dealer Request ─────────────────────────────────────────────────────
// Sent to POST /api/dealers
// dealerId and createdDate are auto-generated by SQL Server, so we omit them.
export interface CreateDealerRequest {
  dealerName: string;
  contactPerson: string;
  phone: string;
  email: string;
  address: string;
  city: string;
}

// ── Update Dealer Request ─────────────────────────────────────────────────────
// Sent to PUT /api/dealers/:id
// All fields are optional because user may only update one field.
export interface UpdateDealerRequest {
  dealerName?: string;
  contactPerson?: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  status?: boolean;
}

// ── Dealer List Params ────────────────────────────────────────────────────────
// Query parameters sent to GET /api/dealers
// Used for search, filter, and pagination.
export interface DealerListParams {
  page: number;
  limit: number;
  search?: string;       // searches dealerName, contactPerson, city
  status?: boolean;      // true = active only, false = inactive only
  city?: string;         // filter by city
}

// ── Dealer State ──────────────────────────────────────────────────────────────
// Shape of the dealers slice in Redux store.
export interface DealerState {
  list: {
    data: Dealer[];
    total: number;
    page: number;
    totalPages: number;
    isLoading: boolean;
    error: string | null;
  };
  selected: {
    data: Dealer | null;
    isLoading: boolean;
    error: string | null;
  };
  isCreating: boolean;
  isUpdating: boolean;
  isDeleting: boolean;
}
